Model:
    CharSet: [' ', 壹, 玖, '1', '9', 捌, '-', '8', '5', 零, 伍, +, '4', 柒, '2', '0', 加,
        '7', 减, 陆, '6', '=', x, 贰, 肆, '?', 叁, '3', 乘]
    ImageChannel: 3
    ImageHeight: 128
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: /home/wangjie/PycharmProjects/dddd_trainer/projects/piaoxingqiu/datasets/images
    Project: piaoxingqiu
    Val: 0.1
Train:
    BATCH_SIZE: 32
    CNN: {NAME: efficientnet_v2_s, PRETRAINED: true}
    DROPOUT: 0.5
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 200
    TARGET: {Accuracy: 0.98, Cost: 0.05, Epoch: 10}
    TEST_BATCH_SIZE: 128
    TEST_STEP: 100
    VER: v2009_32_d05_lr01_pretrained_merge
