Model:
    CharSet: [' ', '0', '-', '7', '?', '3', '5', '4', '=', +, '8', x, '2', '9', '6',
        '1']
    ImageChannel: 3
    ImageHeight: 128
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: /home/wangjie/PycharmProjects/dddd_trainer/projects/piaoxingqiu/datasets/images
    Project: piaoxingqiu
    Val: 0.1
Train:
    BATCH_SIZE: 32
    CNN: {NAME: effnetv2_s, PRETRAINED: false}
    DROPOUT: 0.5
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.98, Cost: 0.05, Epoch: 5}
    TEST_BATCH_SIZE: 64
    TEST_STEP: 500
    VER: v4500_32_d05_lr01
